# Generated by Django 4.1.1 on 2022-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
