# Generated by Django 4.1.1 on 2022-10-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_review_blog_score_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category safe URL',
            new_name='blogurl',
        ),
    ]
