# Generated by Django 4.1.1 on 2022-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_rename_blogurl_blog_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="coursedownload",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
