# Generated by Django 4.1.1 on 2022-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_course_coursedownload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coursedownload",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="discount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
